<?php
require_once '../includes/functions.php'; require_admin(); $id=(int)($_GET['id']??$_POST['id']??0);$st=$conn->prepare('SELECT * FROM products WHERE id=? LIMIT 1');$st->bind_param('i',$id);$st->execute();$product=$st->get_result()->fetch_assoc();if(!$product)redirect('products.php');$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
$name=trim($_POST['name']??'');$category=trim($_POST['category']??'');$subcategory=trim($_POST['subcategory']??'');$price=(float)($_POST['price']??0);$stock=(int)($_POST['stock']??0);$image=trim($_POST['image']??'');$short=trim($_POST['short_description']??'');$desc=trim($_POST['description']??'');$featured=isset($_POST['is_featured'])?1:0;
if($name===''||$category===''||$subcategory===''||$price<=0||$image===''||$desc==='')$error='Please complete all required fields.';else{$st=$conn->prepare('UPDATE products SET name=?,category=?,subcategory=?,price=?,stock=?,image=?,short_description=?,description=?,is_featured=? WHERE id=?');$st->bind_param('sssdisssii',$name,$category,$subcategory,$price,$stock,$image,$short,$desc,$featured,$id);$st->execute();flash('notice','Product updated successfully.');redirect('products.php');}}
$pageTitle='Edit Product | GadgetKart';$basePath='../';require '../includes/header.php';
?>
<section class="section"><div class="container narrow"><div class="form-card"><span class="eyebrow">ADMIN</span><h1>Edit Product</h1><?php if($error): ?><div class="alert error"><?= e($error) ?></div><?php endif; ?><form method="post"><input type="hidden" name="id" value="<?= $id ?>"><div class="form-two"><label>Product name<input name="name" required value="<?= e($product['name']) ?>"></label><label>Price<input name="price" type="number" step="0.01" required value="<?= e($product['price']) ?>"></label></div><div class="form-two"><label>Category<select name="category"><option <?= $product['category']==='Mobile Accessories'?'selected':'' ?>>Mobile Accessories</option><option <?= $product['category']==='Computer Accessories'?'selected':'' ?>>Computer Accessories</option><option <?= $product['category']==='Gaming'?'selected':'' ?>>Gaming</option></select></label><label>Subcategory<input name="subcategory" required value="<?= e($product['subcategory']) ?>"></label></div><div class="form-two"><label>Stock<input name="stock" type="number" min="0" required value="<?= e($product['stock']) ?>"></label><label>Image filename<input name="image" required value="<?= e($product['image']) ?>"></label></div><label>Short description<input name="short_description" required value="<?= e($product['short_description']) ?>"></label><label>Full description<textarea name="description" rows="6" required><?= e($product['description']) ?></textarea></label><label class="check"><input type="checkbox" name="is_featured" <?= $product['is_featured']?'checked':'' ?>> Show on home page</label><button class="btn" type="submit">Update Product</button></form></div></div></section>
<?php require '../includes/footer.php'; ?>
